apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myfirstrs
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myfirstcotnainer
        image: nginx:1.30.4
        ports:
        - containerPort: 80