apiVersion: v1
kind: Pod
metadata:
  name: success-pod
spec:
  containers:
  - name: myfirstcontainer
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits: 
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"