apiVersion: v1
kind: Pod
metadata:
  name: fail-pod
spec:
  containers:
  - name: myfirstcontainer
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits: 
        memory: "2Gi"
        cpu: "2"
      requests:
        memory: "2Gi"
        cpu: "2"