apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-app-limit
  namespace: myapp
spec:
  hard:
    requests.cpu: "1"         #Min guaranteed CPU across all pods
    requests.memory: "1Gi"    #Min guaranteed memory across all pods
    limits.cpu: "2"           #max hard ceiling for total CPU usage
    limits.memory: "4Gi"      #max hard ceiling for total memory usage