#To pass the values in plain english, without encoding (stringData)
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
stringData:
  DB_USERNAME: dbadmin
  DB_PASSWORD: secret123

---
#To pass the values in base64 (data)
# apiVersion: v1
# kind: Secret
# metadata:
#   name: db-secret
# data:
#   DB_USERNAME: ZGJhZG1pbg==
#   DB_PASSWORD: c2VjcmV0MTIz
---
#Create secret imperatively

# kubectl create secret generic db-secret --from-literal=DB_USERNAME=dbadmin --from-literal=DB_PASSWORD=secret123
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod1
spec:
  containers:
  - name: myfirstcontainer
    image: busybox
    command: ["sh", "-c", "echo The DB username is $DB_USERNAME && echo The DB password is $DB_PASSWORD && sleep 3600"]
    envFrom:
    - secretRef:
        name: db-secret

---

apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod2
spec:
  containers:
  - name: myfirstcontainer
    image: busybox
    command: ["sh", "-c", "echo The DB username is $DB_USERNAME && sleep 3600"]
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_USERNAME
---


apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod3
spec:
  containers:
  - name: myfirstcontainer
    image: busybox
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: db-secret
